spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dto1
    username: postgres
    password: Urmat0204
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 1212
  error:
    include-stacktrace: always
